import React from 'react';
import { Upload, Search, ArrowRight } from 'lucide-react';
import RegisterComposition from './viz/RegisterComposition';
import { ErrorState } from './ui/States';
import { humanize } from '../lib/labels';
import DataLinkLogo from './DataLinkLogo';

const tones={COMPLETED:'ok',COMPLETED_WITH_ERRORS:'warn',FAILED:'bad',RUNNING:'accent',PROCESSING:'accent',PENDING:'neutral'};
const Signal=({label,value,tone,note})=><div className="overview-signal"><span className="overview-dot" style={{background:'var(--'+tone+')'}}/><p>{label}</p><strong className="num">{Number(value||0).toLocaleString()}</strong><small>{note}</small></div>;

export default function OverviewDashboard({stats,statsError,onRetry,setActiveTab,setSelectedJobId}){
 if(statsError)return <div className="p-6"><ErrorState error={statsError} onRetry={onRetry} title="Overview could not be loaded"/></div>;
 if(!stats)return <div className="overview-loading"><DataLinkLogo className="w-6 h-6"/><span>Reading registry intelligence</span></div>;
 const total=stats.total_records||0,valid=stats.valid_records||0,dup=stats.duplicate_records||0,errors=stats.total_errors||0,incomplete=Math.max(0,total-valid-dup-errors);
 const health=stats.success_rate??(total?(valid/total)*100:0),runs=(stats.recent_jobs||stats.items||[]).slice(0,5),last=runs[0];
 return <main className="overview-canvas">
  <header className="overview-titlebar"><div><p className="overview-kicker">Workspace / Registry</p><h1>Registry intelligence</h1><p>Data quality, ingestion state and the work ahead.</p></div><div className="overview-actions"><button onClick={()=>setActiveTab('records')} className="btn h-9 px-3"><Search className="w-3.5 h-3.5"/>Explore data</button><button onClick={()=>setActiveTab('upload')} className="btn-primary h-9 px-3"><Upload className="w-3.5 h-3.5"/>Ingest register</button></div></header>
  <section className="overview-hero"><div className="overview-hero-main"><p className="overview-kicker">Data workspace</p><strong className="overview-total num">{total.toLocaleString()}</strong><p>records in the active register</p></div><div className="overview-health"><p className="overview-kicker">Validation health</p><strong className="num">{Number(health).toFixed(1)}<em>%</em></strong><p>of ingested rows pass active rules</p><i><b style={{width:Math.min(100,Number(health))+'%'}}/></i></div><div className="overview-signals"><Signal label="Usable" value={valid} tone="ok" note="ready for operations"/><Signal label="Duplicate" value={dup} tone="dup" note="needs resolution"/><Signal label="Incomplete" value={incomplete} tone="warn" note="needs enrichment"/><Signal label="Errors" value={errors} tone="bad" note="failed validation"/></div></section>
  <div className="overview-columns"><section className="overview-region"><header><div><p className="overview-kicker">Data composition</p><h2>Where the register stands</h2></div><span>Live distribution</span></header><RegisterComposition stats={stats}/></section><section className="overview-region"><header><div><p className="overview-kicker">Pipeline</p><h2>Operational state</h2></div><span className={'badge badge-'+(tones[last?.status]||'neutral')}>{last?humanize(last.status):'No runs'}</span></header><dl className="overview-facts"><div><dt>Registers ingested</dt><dd className="num">{(stats.total_files||0).toLocaleString()}</dd></div><div><dt>Processing runs</dt><dd className="num">{(stats.total_jobs||0).toLocaleString()}</dd></div><div><dt>Last activity</dt><dd>{last?.filename||'Awaiting first upload'}</dd></div></dl></section></div>
  <section className="overview-region overview-activity"><header><div><p className="overview-kicker">Recent activity</p><h2>Ingestion history</h2></div><button onClick={()=>setActiveTab('jobs')} className="btn-ghost h-7 px-1">All runs <ArrowRight className="w-3.5 h-3.5"/></button></header>{runs.length?<ul>{runs.map(job=><li key={job.id}><button onClick={()=>{setSelectedJobId?.(job.id);setActiveTab('jobs')}}><span className="num">#{job.id}</span><b>{job.filename}</b><span className={'badge badge-'+(tones[job.status]||'neutral')}>{humanize(job.status)}</span><span className="num">{(job.total_rows||0).toLocaleString()} rows</span></button></li>)}</ul>:<p className="py-8 t-body">No runs yet. Ingest a register to begin.</p>}</section>
 </main>;
}